### PR TITLE
[Issue #49] Bloodseeker retreat logic

### PR DESCRIPTION
**Pull request by pbenologa**
- added additional conditions before bloodseeker retreats, now checks if
he can kill the target and regenerate health before retreating when hp
dips below the threshold

### CODE REVIEW

**Comment by Nostrademous** [comment]
so you don't need to use the getHeroVar("Target") at all there. When I said target earlier I mean the "neutral" in question you are trying to kill.

You can just do "neutral:GetActualDamage(dmg, dmg_type)"

Please don't over-load the global hero variable of "Target"

**Comment by pbenologa** [comment]
Im a bit confused, enlighten me on this one. If i'm inside the DoRetreat function what will I use to get the "neutral" which is defined in DoCleanCamp function?

**Comment by Nostrademous** [comment]
local neutrals = bot:GetNearbyCreeps(EyeRange,true)

**Comment by pbenologa** [comment]
If i use that wouldnt there be a possibility where the selected neutral will be different from the one the bot is attacking? Since the code gets all nearby creeps within the specified radius.

**Comment by Nostrademous** [comment]
table.sort(neutrals, function(n1, n2) return n1:GetHealth() < n2:GetHealth() end) 

After that neutrals[1] should be lowest health... that's the one you check for kill or you retreat

**Comment by pbenologa** [comment]
Okay thanks! I'll update the code. :smile:

**Comment by Keithenneu** [comment]
Thanks, that's cool.

**Pull request merged**
