### PR TITLE
Initial changes for Drow Ranger Bot

### PR DESCRIPTION
**Pull request by pbenologa**

### CODE REVIEW

**Comment by Nostrademous** [comment]
Can you do me 3-4 favors so I can accept pull request:

1) You have: local force = utils.HaveItem(npcBot, "item_hurricane_pike") in two places in item_usage.lua, can you please change the"force" to "pike" or whatever. This is minor cosmetic issue but I am trying to have consistency in variable naming

2) Check bot_viper.lua where we do self:setHeroVar("HasOrbAbility", SKILL_Q). Drow is the same as his Frost Arrows are an orb effect that can be used to harass enemy without pulling aggro. please implement the same way. You need the OutOfRangeCasting initialization too since you use it in UseQ() of ability_use_drow_ranger.lua

3) If you really want to run Drow as Jungler please fill out a Jungler Itemization in "item_purchase_drow_ranger.lua" in addition to the HardCarry table

4) This one I don't care about and perhaps you meant it that way... but they way you setup his UseQ() is to never use Frost Arrow if Gust is available if there is exactly 1 enemy.

**Comment by pbenologa** [comment]
Oh okay i'll refine it further.

1. The first instance of hurricane pike is for movement usage (hurricane pike on self) while the second instance is for defensive purposes where if a enemy hero gets close enough the bot will use hurricane pike on the enemy. So basically 1 item is tagged under MovementItems and DefensiveItems.

2. Oops did not notice that the codes where updated since my last pull.

3. This i'm still looking at since i want drow to start jungling by a specific condition which is level and item timings. Not really a full pledge jungler. I'll use the "item_purchase_viper" as a baseline since its more detailed.

4. Oops did not read the code carefully. Thanks. Ill make the necessary adjustments.

**Comment by Nostrademous** [comment]
regarding 1, I realize what you did. I'm asking for the "local force" to be changed to "local pike" in both spots.

**Comment by pbenologa** [comment]
Yup now that i checked it i changed now. It was the variables you were talking about. Sorry. :smile:

**Comment by Nostrademous** [comment]
Thank you

**Pull request merged**
